sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: RS26F1z8Auqi7GJrmeZC4q/HtCarkUa/Q0DdvtrtMYLieRum6pRtcSJstsq+oMcdnTX13+E1tbuwn2BU7L8rq5UgCf09Plnhl+RaRTFU3VIEveXPojaEfDvgjpl5c0MoXAXjrv7in7dR+Z1H8A8Bduxs98KnRe+8qR37DdI65bJrvXnRFkJBeRvb4hfZSqZ/STeSGb/nGVkFfXpTGfBPNzZIrPvFftLZuNfCmtU0xiG78tQ/tvqAU5hoSOO+XbvJcpwjo+5oVrfUO8If9+hHu/n2CHg27gjbh9bf/KaNjappR04wGjgyc2r4HgRccHss5CkVwE9LOut/ixL5CxorkAKoTbdQeE1KwlISqVvXnMAQEvFKNI08JB3FY/WRdNJO2ocGcGzSiXNS1dagraGXISHQdX9G25tHeetzV+JbIYpGzTb5Kqk8za9G2+Z387gxQfucUMPs/s9i+O3EL4hsWD1t9SqeXMeMpBY61r0pBJt600Owsqh0Ld9VaFmRDkc4l5htuS1nSqwy52rD80vXok5wYzkXSKFs8ekYpkAcAVJhh3YDZKJt/sJBOg0Yl8Xhn8fKFtzy/MKCloY08P1nojnLWW5MlO2xbdBHObB/2/P/2fjcPfKVDMh35yfD24NVPOkRlNkzC4gtdwGLETrlWENwjSygtUeRBR62+EJECzs=
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml'
env:
  global:
  - secure: Z1jNumBe6D/Qd5iLs3OPEZf6r+zwwPVmLVbmV1dGcfue92WczYZz5b9Mj1IRHHbdma4dwGg+z7edqT1a7IE9Z29aSWh/dcvt0NuJY6IjqjGvrhOEMSaRFoRLI0kCArMuwR2bLca7SuLRYn2kgG1d6RhRtwFYX07PY+w6/i8B2qChG1BHTFWC3N3a8monvX+ooOvXd85muRrmZxKq+r85SlPm4ddzu9KwhDeDsKibqe17xSZR3zgikDfV8tEWuIOpRYetSNDC7cPZSX/1MT86dOdAEXWJ5m4YlJgKeNy8AZ2IGW2QwTmYaad0n6ubY1p5MLrlSn3IWAP2P+nk9+f8Tl6eh/FYtGzHOUq0EYCPOY8ohZudae2iD7x70W0/uiV+7rkszMf+m9/QF4/J5jVascKwJumbQaWOhjB+mwJVzNGQdi4kCgl/X9NPf+5Nz3XmLdzFsTsbb/rc7fv+IvcRYMGF82scgObKM5AHLOTRiBzSf07vBElN6qbm9JTCZoXAvUqDatCYPv8XgTBotvr5V6Cg9hAsxO/DQCg/MNBavt6eeqfUTpXJikodAvSCPzm9jYXMjMS8VcOvYTwawLf1LtGFOKBKXUdOWSyUMOid08jzQlxHYvhdNjsB4RkZnMbJoPCNOBLY+MyUd6/InI83Yi+ynF4qOhefL4NzekzoBPc=
  - secure: TGB2UZmbMWU0LqLL9I+U3JCW+h5UoXNxX5hsuyvZGwC7w9iHZ0wm8I0ffNNIsFUxgiuzi2z3ZCNGCF1neah/4wclTSFM0bXZZlx2p7xfi5AWiKb6DrLBWYvc8yqSMg/ErWcQZPkEQdNNJQrsKEYaRSpubKP+2bekuUgdFdb5IWKrUqETB771ZpSz5bnX5m3yUs+mxxR5BRX3YNR4PGOgpyeK8ILlocWylDYmctIfxu/YJTbsF/JtxBFfZGQ5WoV6sUyrsVUyAPVdXmBRTomuKAMV0vn7sKBwhrZ1lGS9vgSAzRo+kD0NlK2fx83klHZSp6R7PsoUs6yZ/bWoT2vvuFScCxB/79WrGzkLBUJcHe5bmCep1rjf3YCZODDCd97zOLddaAGNXnLafp28CZKRtlYHJoKzLUNi3gJn5JkBriJ0hLgmicQGwHvsvusuHigN+tZb3cWoNUgO7BGd9eY1qVxbjsXyiW7XVwGNjo785Ij2EpFT95+9L84cTt/D3ZSmpOsIoPrE0wMuEs8JzJ45T4+OLZ+qH+rQe17Dgg0yB8TbCCLar7ehESC1a3Cp1Hg433QpC9ouo2DonsK8T9tbg/4ksczwYmPGJArU4z8iYFH01DJlZ7UF32qIYmeQSlmbwqDdcVHf2g9TatUCUvxgHZAL0IlmeIAVUCUiL2YLzBM=
